const API = 'https://api.jikan.moe/v4';
const cacheKey = (path) => `zenith:jikan:${path}`;
const known = [
['Sousou no Frieren',52991,2023,'Fantasia',28,9.25],['Fullmetal Alchemist: Brotherhood',5114,2009,'Ação',64,9.11],['Steins;Gate',9253,2011,'Ficção científica',24,9.07],['Hunter x Hunter (2011)',11061,2011,'Aventura',148,9.03],['Gintama',918,2006,'Comédia',201,8.93],['Kaguya-sama: Love is War',37999,2019,'Comédia',12,8.41],['Nichijou',10165,2011,'Comédia',26,8.46],['Daily Lives of High School Boys',11843,2012,'Comédia',12,7.79],['Spy x Family',50265,2022,'Comédia',25,8.45],['Bocchi the Rock!',47917,2022,'Comédia',12,8.76],['Attack on Titan',16498,2013,'Ação',25,8.55],['Violet Evergarden',33352,2018,'Drama',13,8.65],['Jujutsu Kaisen',40748,2020,'Ação',24,8.55],['Demon Slayer: Kimetsu no Yaiba',38000,2019,'Ação',26,8.49],['Mob Psycho 100',32182,2016,'Comédia',12,8.48],['Haikyuu!!',20583,2014,'Esportes',25,8.44],['Your Lie in April',23273,2014,'Drama',22,8.64],['A Silent Voice',28851,2016,'Drama',1,8.94],['Made in Abyss',34599,2017,'Aventura',13,8.65],['Cowboy Bebop',1,1998,'Ficção científica',26,8.75],['Neon Genesis Evangelion',30,1995,'Mecha',26,8.35],['Fruits Basket',38680,2019,'Romance',25,8.21],['Yuri on Ice',32995,2016,'Esportes',12,7.90],['The Apothecary Diaries',54492,2023,'Mistério',24,8.89]];
const posterUrls={52991:'https://poster4.me/wp-content/uploads/frieren_6.jpg',9253:'https://image.tmdb.org/t/p/original/96R4bV7dB8ramaWceNKsxvJgCUd.jpg'};
const offlineExtras=[['A-Channel',9776,2011,'Comedy',12,6.78],['Baka to Test to Shoukanjuu Ni!',9963,2011,'Comedy',13,7.23],['Ben-To',10396,2011,'Comedy',12,7.12],['Gintama\'',10049,2011,'Comedy',51,8.87],['Level E',9834,2011,'Comedy',13,7.44],['Mitsudomoe Zouryouchuu!',9980,2011,'Comedy',8,7.47],['Morita-san wa Mukuchi.',10527,2011,'Comedy',13,6.69],['Nyanpire The Animation',10134,2011,'Comedy',12,6.45],['SKET Dance',9863,2011,'Comedy',77,8.20],['Working\'!!',10521,2011,'Comedy',13,7.97],['Yondemasu yo, Azazel-san.',10216,2011,'Comedy',13,7.48]];
const staticCatalog=[...known,...offlineExtras].map(([title,mal_id,year,genre,episodes,score])=>({mal_id,title,title_english:title,year,episodes,score,type:'TV',images:{jpg:{large_image_url:posterUrls[mal_id]}},genres:[{name:genre,mal_id:genre==='Comedy'||genre==='Comédia'?4:undefined}],synopsis:`${title} — título real listado no catálogo demonstrativo.`}));
const currentSeason=[['Mushoku Tensei III: Isekai Ittara Honki Dasu',59193],['Youjo Senki II',49233],['Super no Ura de Yani Suu Futari',62076],['Bleach: Sennen Kessen-hen - Kashin-tan',60636],['Otome Game Sekai wa Mob ni Kibishii Sekai desu 2',54000],['Grand Blue Season 3',62542],['Seihantai na Kimi to Boku 2nd Season',63832],['Yani Neko',63403],['Mahou Shoujo Madoka Magica Movie 4: Walpurgis no Kaiten',48820],['Re:Zero kara Hajimeru Isekai Seikatsu 4th Season',61316],['Steel Ball Run: JoJo no Kimyou na Bouken',61469],['Chainsaw Man Movie: Reze-hen',57555],['Sousou no Frieren',52991],['Spy x Family',50265]].map(([title,mal_id])=>({mal_id,title,title_english:title,year:2026,episodes:null,score:null,type:'TV',images:{jpg:{}},genres:[],synopsis:''}));
const currentFallback={monday:currentSeason.slice(0,2),tuesday:currentSeason.slice(2,4),wednesday:currentSeason.slice(4,6),thursday:currentSeason.slice(6,8),friday:currentSeason.slice(8,10),saturday:currentSeason.slice(10,12),sunday:currentSeason.slice(12)};

export async function request(path) {
  const cached = sessionStorage.getItem(cacheKey(path));
  if (cached) return JSON.parse(cached);
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 12000);
  try {
    const response = await fetch(`${API}${path}`, { signal: controller.signal });
    if (!response.ok) throw new Error(`Catálogo indisponível (${response.status})`);
    const payload = await response.json(); sessionStorage.setItem(cacheKey(path), JSON.stringify(payload)); return payload;
  } finally { clearTimeout(timer); }
}
const empty = (path, fallback=[]) => request(path).catch(() => ({ data: fallback, error: true }));
export const getTop = () => empty('/top/anime?filter=bypopularity&limit=24',staticCatalog);
export const getSeason = async () => { try { const pages=await Promise.all([1,2].map(page=>request(`/seasons/now?limit=25&page=${page}`))); return {data:pages.flatMap(x=>x.data||[])}; } catch { return {data:staticCatalog.slice(0,12),error:true}; } };
export const getUpcoming = () => request('/seasons/upcoming?limit=24').then(r=>({data:r.data||[]})).catch(()=>({data:[]}));
const staticSchedule={monday:staticCatalog.slice(0,4),tuesday:staticCatalog.slice(4,8),wednesday:staticCatalog.slice(8,12),thursday:staticCatalog.slice(12,16),friday:staticCatalog.slice(16,20),saturday:staticCatalog.slice(20,22),sunday:staticCatalog.slice(22)};
const staticGenreIds={Action:1,Adventure:2,Comedy:4,Mystery:7,Drama:8,Ecchi:9,Fantasy:10,Hentai:12,Historical:13,Horror:14,Kids:15,'Martial Arts':17,Mecha:18,Music:19,Romance:22,School:23,'Sci-Fi':24,Shoujo:25,'Girls Love':26,Shounen:27,'Boys Love':28,Space:29,Sports:30,'Super Power':31,Vampire:32,'Slice of Life':36,Supernatural:37,Military:38,Seinen:42,Josei:43};
const staticGenres=['Action','Adventure','Comedy','Drama','Fantasy','Horror','Mystery','Romance','Sci-Fi','Slice of Life','Sports','Supernatural','Suspense','Ecchi','Hentai','Boys Love','Girls Love','Gourmet','Historical','Martial Arts','Mecha','Military','Music','Parody','Psychological','Racing','Samurai','School','Space','Super Power','Vampire','Workplace','Adult Cast','Anthropomorphic','CGDCT','Childcare','Combat Sports','Crossdressing','Delinquents','Detective','Educational','Gag Humor','High Stakes Game','Idols (Female)','Idols (Male)','Isekai','Iyashikei','Love Polygon','Magical Sex Shift','Mahou Shoujo','Medical','Organized Crime','Otaku Culture','Performing Arts','Pets','Reverse Harem','Reincarnation','Showbiz','Strategy Game','Survival','Team Sports','Time Travel','Video Game','Visual Arts','Seinen','Shoujo','Shounen','Josei','Kids'].map((name,index)=>({mal_id:staticGenreIds[name]||9000+index,name}));
export const getSchedule = async () => { const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']; try { const season=await getSeason(); const current=season.data||[]; return {data:Object.fromEntries(days.map(day=>[day,current.filter(a=>a.broadcast?.day?.toLowerCase()===day)]))}; } catch { return {data:{}}; } };
export const getGenres = async () => { const sources=await Promise.allSettled(['demographics','genres','explicit_genres','themes'].map(filter=>request(`/genres/anime?filter=${filter}`))); const live=sources.flatMap(result=>result.status==='fulfilled'?(result.value.data||[]):[]); const seen=new Set(); const cleaned=[...live,...staticGenres].filter(g=>{const label=g.name==='Erotica'?'Ecchi':g.name;if(seen.has(label))return false;seen.add(label);return true;}).map(g=>({...g,name:g.name==='Erotica'?'Ecchi':g.name})); return {data:cleaned}; };
export const searchAnime = ({ query='', genre='', type='', year='', season='', minimum='', order='popularity' } = {}) => {
  const p = new URLSearchParams({ limit:'25', order_by:order, sort:'asc' });
  if (query) p.set('q', query); if (genre) p.set('genres', genre); if (type) p.set('type', type.toLowerCase()); if (minimum) p.set('min_score', minimum);
  if (year) { p.set('start_date', `${year}-01-01T00:00:00+00:00`); p.set('end_date', `${year}-12-31T23:59:59+00:00`); }
  const seasons={Verão:'summer',Outono:'fall',Inverno:'winter',Primavera:'spring'};
  if(season && year) return empty(`/seasons/${year}/${seasons[season]}`).then(r=>({ ...r, data:(r.data||[]).filter(a=>(!genre||a.genres?.some(g=>String(g.mal_id)===String(genre)))&&(!type||a.type===type)&&(!minimum||a.score>=Number(minimum))) }));
  const fallback=staticCatalog.filter(a=>(!query||a.title.toLowerCase().includes(query.toLowerCase()))&&(!genre||a.genres?.some(g=>String(g.mal_id)===String(genre)))&&(!type||a.type===type)&&(!year||String(a.year)===String(year))&&(!minimum||a.score>=Number(minimum)));
  return request(`/anime?${p}&page=1`).then(async first=>{const max=Math.min(10,first.pagination?.last_visible_page||1);const rest=[];for(let page=2;page<=max;page++){await new Promise(resolve=>setTimeout(resolve,700));try{rest.push(await request(`/anime?${p}&page=${page}`))}catch{break}}return {data:[...(first.data||[]),...rest.flatMap(x=>x.data||[])]}}).catch(()=>({data:fallback}));
};
export const getAnime = (id) => empty(`/anime/${id}/full`);
