import { useEffect, useMemo, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { Bell, Bookmark, ChevronLeft, Clock3, Flame, Heart, Home as HomeIcon, ListVideo, LoaderCircle, LogIn, Menu, MessageSquarePlus, Play, Search, Send, Settings2, Sparkles, Star, UserRound, X } from 'lucide-react';
import { getAnime, getGenres, getSchedule, getSeason, getTop, getUpcoming, searchAnime } from './api/jikan';
import { read, uid, write } from './lib/storage';
import heroArt from './assets/zenith-hero.png';

const img = (a) => a?.images?.webp?.large_image_url || a?.images?.jpg?.large_image_url || a?.images?.jpg?.image_url;
const normalize = (a) => ({ id: a.mal_id, title: a.title_english || a.title, image: img(a), score: a.score, episodes: a.episodes, year: a.year || a.aired?.prop?.from?.year, synopsis: a.synopsis, trailer: a.trailer?.embed_url, genres: [...(a.genres||[]),...(a.explicit_genres||[]),...(a.themes||[]),...(a.demographics||[])].map((g) => g.name), type: a.type });
const statuses = ['Assistindo', 'Quero assistir', 'Concluído', 'Pausado'];

function useLocal(name, fallback) {
  const [value, setValue] = useState(() => read(name, fallback));
  useEffect(() => write(name, value), [name, value]);
  return [value, setValue];
}

function App() {
  const [user, setUser] = useLocal('user', null);
  const [watchlist, setWatchlist] = useLocal('watchlist', [{id:52991,title:'Sousou no Frieren',image:'https://poster4.me/wp-content/uploads/frieren_6.jpg',episodes:28,progress:7,status:'Assistindo'},{id:50265,title:'Spy x Family',episodes:25,progress:0,status:'Quero assistir'}]);
  const [reviews, setReviews] = useLocal('reviews', []);
  const [feedback, setFeedback] = useLocal('feedback', []);
  const [history, setHistory] = useLocal('history', []);
  const state = { user, setUser, watchlist, setWatchlist, reviews, setReviews, feedback, setFeedback, history, setHistory };
  return <><Header state={state} /><main><Routes>
    <Route path="/" element={<Home />} /><Route path="/browse" element={<Browse state={state} />} />
    <Route path="/show/:id" element={<Details state={state} />} /><Route path="/watch/:id" element={<Watch state={state} />} />
    <Route path="/calendar" element={<ReleaseCalendar />} /><Route path="/coming-soon" element={<ComingSoon />} />
    <Route path="/watchlist" element={<Watchlist state={state} />} /><Route path="/profile" element={<Profile state={state} />} /><Route path="/feedback" element={<Feedback state={state} />} />
    <Route path="*" element={<Home />} />
  </Routes></main><Footer /></>;
}

function Header({ state }) {
  const [open, setOpen] = useState(false); const [login, setLogin] = useState(false);
  return <header className="header"><Link to="/" className="brand"><span>ZENITH</span> STREAM</Link><nav className={open ? 'open' : ''}>
    <NavLink to="/" end><HomeIcon size={16}/>Início</NavLink><NavLink to="/browse"><Search size={16}/>Explorar</NavLink><NavLink to="/calendar"><Clock3 size={16}/>Calendário</NavLink><NavLink to="/coming-soon"><Sparkles size={16}/>Em breve</NavLink><NavLink to="/watchlist"><ListVideo size={16}/>Minha lista</NavLink><NavLink to="/feedback"><MessageSquarePlus size={16}/>Feedback</NavLink>
  </nav><div className="header-actions"><Link className="icon-button" to="/browse" aria-label="Buscar"><Search size={18}/></Link>{state.user ? <Link className="avatar" title="Perfil" to="/profile">{state.user.name[0].toUpperCase()}</Link> : <button className="login-button" onClick={() => setLogin(true)}><LogIn size={16}/>Entrar</button>}<button className="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div>
    {login && <Login onClose={() => setLogin(false)} state={state}/>}</header>;
}

function Login({ onClose, state }) { const [mode,setMode]=useState('login'); const [name, setName] = useState(state.user?.name||''); const [email, setEmail] = useState(state.user?.email||''); return <div className="modal-backdrop"><section className="modal"><button className="close" onClick={onClose}><X/></button><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Entrar</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Criar conta</button></div><span className="eyebrow">BEM-VINDO AO ZENITH</span><h2>{mode==='login'?'Acesse sua':'Crie sua'}<br/><i>sessão.</i></h2><p>Use e-mail e nome para demonstrar a área logada, listas, progresso e perfil.</p>{mode==='register'&&<input placeholder="Seu nome" value={name} onChange={e=>setName(e.target.value)}/>}<input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha"/><button className="primary wide" onClick={() => { if(email && (mode==='login'||name)) { state.setUser({name:name||email.split('@')[0], email}); onClose(); }}}>{mode==='login'?'Entrar':'Cadastrar'} <Play size={15}/></button></section></div>; }

function Home() { const [top, setTop] = useState([]); const [season, setSeason] = useState([]); const [loading,setLoading]=useState(true); useEffect(()=>{Promise.all([getTop(),getSeason()]).then(([a,b])=>{setTop(a.data.map(normalize));setSeason(b.data.map(normalize));}).finally(()=>setLoading(false));},[]); if(loading) return <Loading/>; const featured=top[0]; return <><section className="hero" style={{'--hero':`url(${featured?.image||heroArt})`}}><div className="hero-shade"/><div className="hero-content"><span className="eyebrow"><Sparkles size={14}/> EXPERIÊNCIA DE STREAMING · DEMO</span><h1>{featured?.title || 'Catálogo em atualização'}</h1><p>Uma interface original de streaming para explorar títulos, abrir a página de exibição e apresentar como seria uma plataforma com catálogo licenciado.</p><div className="metadata"><span><Star size={15} fill="currentColor"/> {featured?.score ?? '—'}</span><span>{featured?.year}</span><span>{featured?.episodes || '?'} episódios</span></div><div className="hero-cta"><Link className="primary" to={featured?`/watch/${featured.id}`:'/browse'}><Play size={17} fill="currentColor"/>Abrir player</Link><Link className="secondary" to="/browse">Explorar catálogo</Link></div></div></section><Shelf title="Em alta para assistir" icon={<Flame/>} items={top.slice(1,9)}/><Shelf title="Lançamentos da temporada" icon={<Bell/>} items={season.slice(0,8)}/><DailyReleases/></> }
function DailyReleases(){const [data,setData]=useState({});useEffect(()=>{getSchedule().then(x=>setData(x.data||{}));},[]);const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];return <section className="shelf"><div className="section-title"><div><Clock3/><h2>Estreias da semana</h2></div><Link to="/calendar">Calendário completo</Link></div><div className="daily-row">{days.map(day=><Link to="/calendar" className="day-card" key={day}><b>{({monday:'SEG',tuesday:'TER',wednesday:'QUA',thursday:'QUI',friday:'SEX',saturday:'SÁB',sunday:'DOM'})[day]}</b><span>{data[day]?.length||0} lançamentos</span></Link>)}</div></section>}

function Shelf({title, icon, items}) { return <section className="shelf"><div className="section-title"><div>{icon}<h2>{title}</h2></div><Link to="/browse">Ver todos</Link></div><div className="card-row">{items.map(a=><AnimeCard anime={a} key={a.id}/>)}</div></section> }
function Poster({anime, className=''}) { return <div className={`poster ${className}`} data-title={anime.title}><img src={anime.image} alt={anime.title} onLoad={e=>e.currentTarget.nextElementSibling.style.display='none'} onError={e=>e.currentTarget.style.display='none'}/><div className="poster-art"><span>ZENITH<br/>CATÁLOGO</span><strong>{anime.title}</strong><i/></div></div> }
function AnimeCard({anime}) { return <Link className="anime-card" to={`/show/${anime.id}`}><div className="card-visual"><Poster anime={anime}/><span className="score"><Star size={12} fill="currentColor"/>{anime.score||'—'}</span><span className="availability">INDISPONÍVEL</span><div className="play-overlay"><Play fill="currentColor"/></div></div><h3>{anime.title}</h3><p>{anime.year || 'Em breve'} · {anime.episodes || '?'} eps</p></Link> }

function Browse({state}) {
  const [query,setQuery]=useState(''); const [genre,setGenre]=useState(''); const [genres,setGenres]=useState([]); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [type,setType]=useState(''); const [year,setYear]=useState(''); const [season,setSeason]=useState(''); const [minimum,setMinimum]=useState('');
  const selectedGenre=genres.find(g=>String(g.mal_id)===genre)?.name;
  const run=async(next={})=>{const filters={query,genre,type,year,season,minimum,...next};setLoading(true);try{const r=await searchAnime(filters);setItems((r.data||[]).map(normalize));if(filters.query.trim())state.setHistory(h=>[filters.query,...h.filter(x=>x!==filters.query)].slice(0,6));}finally{setLoading(false)}};
  useEffect(()=>{getGenres().then(x=>setGenres(x.data));run();},[]);
  const change=(setter,key)=>(e)=>{setter(e.target.value);run({[key]:e.target.value})};
  const visible=items.filter(a=>{if(selectedGenre!=='Hentai'&&a.genres.includes('Hentai'))return false;if(selectedGenre==='Ecchi'&&(a.genres.includes('Boys Love')||a.genres.includes('Girls Love')))return false;return true});
  return <section className="page"><span className="eyebrow">CATÁLOGO DE STREAMING</span><h1>Encontre seu próximo <i>universo.</i></h1><div className="search-bar"><Search/><input value={query} placeholder="Título, tema, personagem ou palavra-chave…" onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()}/><button className="primary" onClick={()=>run()}>Buscar</button></div>{state.history.length>0&&<div className="history"><Clock3 size={15}/><span>Recentes:</span>{state.history.map(x=><button key={x} onClick={()=>{setQuery(x);run({query:x})}}>{x}</button>)}</div>}<div className="advanced-filters"><select value={type} onChange={change(setType,'type')}><option value="">Todos os tipos</option>{['TV','Movie','OVA','ONA','Special','Music','CM','PV','TV Special'].map(x=><option key={x}>{x}</option>)}</select><select value={year} onChange={change(setYear,'year')}><option value="">Qualquer ano</option>{Array.from({length:66},(_,i)=>2026-i).map(y=><option key={y}>{y}</option>)}</select><select value={season} onChange={change(setSeason,'season')}><option value="">Qualquer temporada</option><option>Verão</option><option>Outono</option><option>Inverno</option><option>Primavera</option></select><select value={minimum} onChange={change(setMinimum,'minimum')}><option value="">Qualquer nota</option><option value="9">9.0+</option><option value="8">8.0+</option><option value="7">7.0+</option></select></div><div className="genre-bar"><button className={!genre?'selected':''} onClick={()=>{setGenre('');run({genre:''})}}>Todos os gêneros</button>{genres.map(g=><button className={genre===String(g.mal_id)?'selected':''} key={g.mal_id} onClick={()=>{setGenre(String(g.mal_id));run({genre:String(g.mal_id)})}}>{g.name}</button>)}</div>{loading?<Loading/>:<><p className="result-count">{visible.length} títulos reais encontrados — carregamos até 100 resultados por pesquisa.</p><div className="grid">{visible.map(a=><AnimeCard anime={a} key={a.id}/>)}</div>{!visible.length&&<EmptyCatalog/>}</>}</section>
}

function Details({state}) { const {id}=useParams(); const [anime,setAnime]=useState(null); const [busy,setBusy]=useState(true); const [status,setStatus]=useState('Quero assistir'); const [rating,setRating]=useState(0); const [comment,setComment]=useState(''); useEffect(()=>{getAnime(id).then(x=>setAnime(normalize(x.data))).finally(()=>setBusy(false));},[id]); if(busy)return <Loading/>; const saved=state.watchlist.find(x=>x.id===anime.id); const save=()=>state.setWatchlist(list=>{const next={...anime,status,progress:saved?.progress||0};return saved?list.map(x=>x.id===anime.id?next:x):[next,...list]}); const reviews=state.reviews.filter(x=>x.animeId===anime.id); return <section className="detail"><div className="detail-backdrop" style={{backgroundImage:`url(${heroArt})`}}/><div className="detail-layout"><Poster anime={anime} className="detail-poster"/><div className="detail-main"><span className="eyebrow">{anime.type || 'ANIME'} · {anime.year || 'EM BREVE'} · CATÁLOGO DEMO</span><h1>{anime.title}</h1><div className="metadata"><span><Star size={15} fill="currentColor"/>{anime.score||'N/A'}</span><span>{anime.episodes||'?'} episódios</span>{anime.genres.slice(0,3).map(x=><span key={x}>{x}</span>)}</div><p>{anime.synopsis || 'Sem sinopse disponível.'}</p><div className="unavailable">Este título é exibido apenas como referência de catálogo. A reprodução exige licença de distribuição.</div><div className="detail-actions"><Link className="primary" to={`/watch/${anime.id}`}><Play size={16} fill="currentColor"/>Abrir player demo</Link><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select><button className="secondary icon-text" onClick={save}><Bookmark size={17} fill={saved?'currentColor':'none'}/>{saved?'Na sua lista':'Adicionar à lista'}</button></div></div></div><section className="reviews"><h2>Comunidade</h2><div className="review-form">{state.user?<><div className="rating">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)}><Star fill={n<=rating?'currentColor':'none'}/></button>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Deixe sua opinião sobre este título…"/><button className="primary" onClick={()=>{if(rating&&comment){state.setReviews(r=>[{id:uid(),animeId:anime.id,author:state.user.name,rating,comment,date:new Date().toLocaleDateString('pt-BR')},...r]);setRating(0);setComment('')}}}>Publicar avaliação</button></>:<p>Entre para avaliar e comentar títulos.</p>}</div>{reviews.length?reviews.map(r=><article className="review" key={r.id}><div className="review-avatar">{r.author[0]}</div><div><b>{r.author}</b><span>{'★'.repeat(r.rating)} <small>{r.date}</small></span><p>{r.comment}</p></div></article>):<p className="muted">Ainda não há avaliações. Seja a primeira pessoa a comentar.</p>}</section></section> }

function Watch({state}) { const {id}=useParams(); const [anime,setAnime]=useState(null); const [speed,setSpeed]=useState('1'); useEffect(()=>{getAnime(id).then(x=>setAnime(normalize(x.data)));},[id]); if(!anime)return <Loading/>; return <section className="watch-page"><Link className="back" to={`/show/${id}`}><ChevronLeft/>Voltar aos detalhes</Link><div className="player unavailable-player" style={{backgroundImage:`linear-gradient(90deg,rgba(9,8,14,.9),rgba(9,8,14,.45)),url(${heroArt})`}}><div><span className="eyebrow">REPRODUÇÃO PROTEGIDA</span><h2>Conteúdo indisponível</h2><p>Esta interface demonstra o player da plataforma. A exibição é liberada somente para obras com direitos de distribuição.</p><button className="secondary"><Play size={16}/>Prévia indisponível</button></div></div><div className="watch-tools"><div><span className="eyebrow">PLAYER DE DEMONSTRAÇÃO</span><h1>{anime.title}</h1><p>Controle de qualidade, episódios e reprodução para conteúdo licenciado.</p></div><label><Settings2 size={17}/>Velocidade<select value={speed} onChange={e=>setSpeed(e.target.value)}>{['0.5','0.75','1','1.25','1.5','1.75','2'].map(x=><option key={x}>{x}x</option>)}</select></label></div><p className="player-note">A velocidade é uma demonstração da interface. Em uma implantação real, esse controle depende de um provedor de vídeo licenciado que exponha essa capacidade.</p></section> }

function ReleaseCalendar(){const [schedule,setSchedule]=useState({});useEffect(()=>{getSchedule().then(x=>setSchedule(x.data||{}));},[]);const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];return <section className="page"><span className="eyebrow">GRADE SEMANAL</span><h1>Calendário de <i>lançamentos.</i></h1><div className="calendar-grid">{days.map(day=><article key={day} className="calendar-day"><h2>{({monday:'Segunda',tuesday:'Terça',wednesday:'Quarta',thursday:'Quinta',friday:'Sexta',saturday:'Sábado',sunday:'Domingo'})[day]}</h2>{(schedule[day]||[]).slice(0,10).map(a=><Link key={a.mal_id} to={`/show/${a.mal_id}`}>{a.title}</Link>)}{!schedule[day]?.length&&<p>Sem dados no momento.</p>}</article>)}</div></section>}
function ComingSoon(){const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);useEffect(()=>{getUpcoming().then(x=>setItems((x.data||[]).map(normalize))).finally(()=>setLoading(false));},[]);return <section className="page"><span className="eyebrow">ANUNCIADOS</span><h1>Chegando <i>em breve.</i></h1><p className="lead">Somente anúncios futuros da fonte pública; títulos já em exibição não entram aqui.</p>{loading?<Loading/>:items.length?<div className="grid">{items.map(a=><AnimeCard anime={a} key={a.id}/>)}</div>:<div className="empty"><Sparkles/><h2>Nenhum anúncio futuro disponível agora</h2><p>Esta lista é atualizada automaticamente quando a fonte pública publica novos anúncios.</p></div>}</section>}
function Profile({state}){const [photo,setPhoto]=useState(state.user?.photo||'');const [theme,setTheme]=useState(state.user?.theme||'violet');if(!state.user)return <section className="page"><Empty/></section>;const eps=state.watchlist.reduce((sum,x)=>sum+(x.progress||0),0);const level=eps>=151?['Super Otaku','✦']:eps>=57?['Otaku','◈']:eps>=25?['Fan','✧']:['Appreciator','○'];const applyTheme=value=>{setTheme(value);state.setUser({...state.user,theme:value})};return <section className={`page narrow profile-theme ${theme}`}><span className="eyebrow">SEU PERFIL</span><h1>{state.user.name}</h1><div className="profile-card"><div className="profile-photo">{photo?<img src={photo} alt="Perfil"/>:state.user.name[0]}</div><label className="secondary">Alterar foto<input type="file" accept="image/*" hidden onChange={e=>{const file=e.target.files?.[0];if(file){const url=URL.createObjectURL(file);setPhoto(url);state.setUser({...state.user,photo:url})}}}/></label><div className="love-meter"><span>{level[1]}</span><div><b>Anime love meter</b><strong>{level[0]}</strong></div></div><p>O status evolui conforme episódios marcados como assistidos.</p></div><section className="profile-customizer"><span className="eyebrow">PERSONALIZAÇÃO</span><h2>Seu espaço, seu tema.</h2><p>Escolha um fundo e uma atmosfera visual para o seu perfil.</p><div className="theme-options">{[['violet','Violeta'],['ocean','Oceano'],['sunset','Pôr do sol'],['sakura','Sakura'],['midnight','Meia-noite']].map(([id,label])=><button key={id} className={theme===id?'chosen':id} onClick={()=>applyTheme(id)}><i className={id}/>{label}</button>)}</div></section><div className="profile-list"><div className="section-title"><div><ListVideo/><h2>Minha lista</h2></div><Link to="/watchlist">Abrir lista</Link></div>{state.watchlist.map(a=><Link key={a.id} to={`/show/${a.id}`}>{a.title}<span>{a.status}</span></Link>)}</div></section>}
function EmptyCatalog(){return <div className="empty"><Search/><h2>Não foi possível carregar resultados agora</h2><p>O catálogo público pode estar limitando requisições. Aguarde alguns segundos e tente novamente.</p></div>}

function Watchlist({state}) { const nav=useNavigate(); const [filter,setFilter]=useState('Todos'); const list=state.watchlist.filter(x=>filter==='Todos'||x.status===filter); const update=(id,patch)=>state.setWatchlist(items=>items.map(x=>x.id===id?{...x,...patch}:x)); return <section className="page"><span className="eyebrow">SUA BIBLIOTECA</span><h1>Continue de onde <i>parou.</i></h1>{!state.user&&<div className="notice"><UserRound/>Crie um perfil para manter esta lista entre sessões do navegador.</div>}<div className="filters">{['Todos',...statuses].map(s=><button key={s} className={filter===s?'selected':''} onClick={()=>setFilter(s)}>{s}</button>)}</div>{list.length?<div className="watchlist">{list.map(a=><article className="watch-entry" key={a.id}><img src={a.image} alt=""/><div><span className="eyebrow">{a.status}</span><h2>{a.title}</h2><p>Episódio {a.progress||0} de {a.episodes||'?'}</p><div className="progress"><i style={{width:`${Math.min(100,(a.progress||0)/(a.episodes||12)*100)}%`}}/></div><div className="entry-actions"><button onClick={()=>update(a.id,{progress:Math.max(0,(a.progress||0)-1)})}>− Episódio</button><button onClick={()=>update(a.id,{progress:Math.min(a.episodes||999,(a.progress||0)+1)})}>+ Episódio</button><button className="linkish" onClick={()=>nav(`/show/${a.id}`)}>Detalhes</button></div></div></article>)}</div>:<Empty/>}</section> }

function Feedback({state}) { const [type,setType]=useState('Sugestão'); const [message,setMessage]=useState(''); const [sent,setSent]=useState(false); return <section className="page narrow"><span className="eyebrow">MELHORIA CONTÍNUA</span><h1>Ajude a elevar o <i>ZENITH.</i></h1><p className="lead">Encontrou algo ou tem uma ideia? Seu feedback fica salvo localmente nesta demonstração.</p><div className="feedback-box"><select value={type} onChange={e=>setType(e.target.value)}><option>Sugestão</option><option>Erro</option><option>Conteúdo</option><option>Outro</option></select><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Conte o que você gostaria de ver…"/><button className="primary" onClick={()=>{if(message.trim()){state.setFeedback(x=>[{id:uid(),type,message,createdAt:new Date().toISOString()},...x]);setMessage('');setSent(true)}}}><Send size={16}/>Enviar feedback</button>{sent&&<p className="success">Obrigado — sua mensagem foi registrada.</p>}</div></section> }

function Empty(){return <div className="empty"><Heart/><h2>Sua lista ainda está vazia</h2><p>Explore o catálogo e guarde os títulos que quer assistir.</p><Link className="primary" to="/browse">Explorar catálogo</Link></div>}
function Loading(){return <div className="loading"><LoaderCircle/><span>Carregando o universo ZENITH…</span></div>}
function Footer(){return <footer><b>ZENITH STREAM</b><span className="footer-name">Latinha</span></footer>}
export default App;
